apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.ClusterRoleName | default "kubechecks-remote-clusterrole" }}
rules:
  - apiGroups: ['argoproj.io']
    resources: ['applications', 'appprojects', 'applicationsets', 'services']
    verbs: ['get', 'list', 'watch']
  - apiGroups: [''] # The core API group, which is indicated by an empty string
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']